version: '3.8'

services:
  runner:
    image: rke-github-selfhosted-runner:latest
    scale: 3
    build:
      context: .
      args:
        RUNNER_VERSION: $RUNNER_VERSION
    environment:
      GH_OWNER:         $GH_OWNER
      GH_REPOSITORY:    $GH_REPOSITORY
      GH_TOKEN:         $GH_TOKEN
