name: test-with-container

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: self-hosted
    container:
      image: maven:3-eclipse-temurin-21

    steps:
      - name: Checkout action
        uses: actions/checkout@v4
